name: 'Vercel Deployment Action'
description: 'Automatically deploy your applications to Vercel with GitHub Actions. Features PR previews, custom domains, and seamless integration.'
author: 'Jai Sharma'

inputs:
  GITHUB_TOKEN:
    description: |
      GitHub authentication token for API access. Automatically provided by GitHub Actions.
    required: false
  VERCEL_TOKEN:
    description: |
      Your Vercel authentication token. Get it from your Vercel account settings.
    required: false
  VERCEL_PROJECT_ID:
    description: |
      Your Vercel project identifier. Found in your project's .vercel/project.json file.
    required: false
  VERCEL_ORG_ID:
    description: |
      Your Vercel organization identifier. Found in your project's .vercel/project.json file.
    required: false
  PRODUCTION:
    description: |
      Deploy to production environment. Set to false for preview deployments (default: true).
    required: false
  PREBUILT:
    description: |
      Deploy a pre-built project without running build commands (default: false).
    required: false
  GITHUB_DEPLOYMENT:
    description: |
      Create a GitHub deployment record for tracking (default: true).
    required: false
  CREATE_COMMENT:
    description: |
      Add deployment information as a comment on pull requests (default: true).
    required: false
  DELETE_EXISTING_COMMENT:
    description: |
      Remove previous deployment comments when redeploying (default: true).
    required: false
  ATTACH_COMMIT_METADATA:
    description: |
      Include commit information in the Vercel deployment metadata (default: true).
    required: false
  DEPLOY_PR_FROM_FORK:
    description: |
      Enable deployments for pull requests from forked repositories (default: false).
    required: false
  PR_LABELS:
    description: |
      Labels to add to pull requests after deployment. Set to false to disable (default: deployed).
    required: false
  ALIAS_DOMAINS:
    description: |
      Custom domain aliases to assign to your deployment.
    required: false
  PR_PREVIEW_DOMAIN:
    description: |
      Custom domain template for pull request preview deployments.
    required: false
  VERCEL_SCOPE:
    description: |
      Vercel team or user scope for the deployment commands.
    required: false
  GITHUB_DEPLOYMENT_ENV:
    description: |
      Custom environment name for GitHub deployment records.
    required: false
  TRIM_COMMIT_MESSAGE:
    description: |
      Truncate commit messages to subject line only in deployment metadata (default: false).
    required: false
  BUILD_ENV:
    description: |
      Environment variables to pass to the build process.
    required: false
  WORKING_DIRECTORY:
    description: |
      Directory where Vercel CLI commands will be executed.
    required: false
  FORCE:
    description: |
      Force deployment by bypassing build cache (default: false).
    required: false

outputs:
  PREVIEW_URL:
    description: 'Primary deployment URL for accessing your application.'
  DEPLOYMENT_URLS:
    description: 'Complete list of all deployment URLs including aliases.'
  DEPLOYMENT_CREATED:
    description: 'Boolean indicating whether a new Vercel deployment was successfully created.'
  COMMENT_CREATED:
    description: 'Boolean indicating whether a deployment comment was added to the PR.'
  DEPLOYMENT_INSPECTOR_URL:
    description: 'URL to inspect and debug your deployment in Vercel dashboard.'
  DEPLOYMENT_UNIQUE_URL:
    description: 'Unique Vercel deployment URL for this specific deployment.'

runs:
  using: 'node24'
  main: 'dist/index.js'

branding:
  icon: 'rocket'
  color: 'blue'
