name: Release CI
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: pnpm install
      - name: Run build command
        run: pnpm run build
      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          GIT_AUTHOR_NAME: "Jai Sharma"
          GIT_AUTHOR_EMAIL: "jai@azodik.com"
          GIT_COMMITTER_NAME: "Azodik Bot"
          GIT_COMMITTER_EMAIL: "jai@azodik.com"
          COMMIT_ASSETS: dist
